/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package nablarch.test.core.http.example.htmlcheck.html5parse;

public interface ParserTreeConstants
{
  public int JJTTEXT = 0;
  public int JJTPCDATA = 1;
  public int JJTATTR = 2;
  public int JJTATTRNAME = 3;
  public int JJTXMLDECL = 4;
  public int JJTDOCUMENT = 5;
  public int JJTHEAD = 6;
  public int JJTHEADELEMENT = 7;
  public int JJTBASE = 8;
  public int JJTMETA = 9;
  public int JJTISINDEX = 10;
  public int JJTLINK = 11;
  public int JJTTITLE = 12;
  public int JJTSCRIPT = 13;
  public int JJTNOSCRIPT = 14;
  public int JJTSTYLE = 15;
  public int JJTHTML = 16;
  public int JJTBODY = 17;
  public int JJTBODYCONTENT = 18;
  public int JJTHEADING = 19;
  public int JJTBLOCK = 20;
  public int JJTPHRASE = 21;
  public int JJTSPECIAL = 22;
  public int JJTFONTDEFINITION = 23;
  public int JJTBASEFONT = 24;
  public int JJTAPPLET = 25;
  public int JJTPARAM = 26;
  public int JJTTEXTTAG = 27;
  public int JJTFONT = 28;
  public int JJTHR = 29;
  public int JJTBR = 30;
  public int JJTIMG = 31;
  public int JJTBUTTON = 32;
  public int JJTH1 = 33;
  public int JJTH2 = 34;
  public int JJTH3 = 35;
  public int JJTH4 = 36;
  public int JJTH5 = 37;
  public int JJTH6 = 38;
  public int JJTADDRESS = 39;
  public int JJTPARAGRAPH = 40;
  public int JJTLIST = 41;
  public int JJTUNORDEREDLIST = 42;
  public int JJTORDEREDLIST = 43;
  public int JJTDEFLIST = 44;
  public int JJTLISTITEM = 45;
  public int JJTDEFLISTITEM = 46;
  public int JJTDT = 47;
  public int JJTDD = 48;
  public int JJTDIR = 49;
  public int JJTMENU = 50;
  public int JJTPREFORMATTED = 51;
  public int JJTDIV = 52;
  public int JJTCENTER = 53;
  public int JJTBLOCKQUOTE = 54;
  public int JJTQ = 55;
  public int JJTFORM = 56;
  public int JJTINPUT = 57;
  public int JJTTABLE = 58;
  public int JJTCOLGROUP = 59;
  public int JJTCOL = 60;
  public int JJTTBODY = 61;
  public int JJTTHEAD = 62;
  public int JJTTFOOT = 63;
  public int JJTCAPTION = 64;
  public int JJTTR = 65;
  public int JJTTH = 66;
  public int JJTTD = 67;
  public int JJTTELETYPE = 68;
  public int JJTITALIC = 69;
  public int JJTBOLD = 70;
  public int JJTUNDERLINE = 71;
  public int JJTSTRIKE = 72;
  public int JJTS = 73;
  public int JJTDEL = 74;
  public int JJTINS = 75;
  public int JJTBIG = 76;
  public int JJTSMALL = 77;
  public int JJTSUBSCRIPT = 78;
  public int JJTSUPERSCRIPT = 79;
  public int JJTEMPHASIZE = 80;
  public int JJTSTRONG = 81;
  public int JJTDEFINITION = 82;
  public int JJTSPAN = 83;
  public int JJTCODE = 84;
  public int JJTSAMPLEOUTPUT = 85;
  public int JJTABBR = 86;
  public int JJTACRONYM = 87;
  public int JJTBDO = 88;
  public int JJTKEYBOARDTEXT = 89;
  public int JJTVARIABLE = 90;
  public int JJTCITATION = 91;
  public int JJTSELECT = 92;
  public int JJTSELECTOPTION = 93;
  public int JJTOPTGROUP = 94;
  public int JJTOPTION = 95;
  public int JJTTEXTAREA = 96;
  public int JJTFIELDSET = 97;
  public int JJTLEGEND = 98;
  public int JJTFRAMESET = 99;
  public int JJTFRAME = 100;
  public int JJTNOFRAMES = 101;
  public int JJTIFRAME = 102;
  public int JJTOBJECT = 103;
  public int JJTLABEL = 104;
  public int JJTANCHOR = 105;
  public int JJTMAP = 106;
  public int JJTAREA = 107;


  public String[] jjtNodeName = {
    "text",
    "pcData",
    "attr",
    "attrName",
    "xmlDecl",
    "document",
    "head",
    "headElement",
    "base",
    "meta",
    "isindex",
    "link",
    "title",
    "script",
    "noscript",
    "style",
    "html",
    "body",
    "bodyContent",
    "heading",
    "block",
    "phrase",
    "special",
    "fontDefinition",
    "basefont",
    "applet",
    "param",
    "textTag",
    "font",
    "hr",
    "br",
    "img",
    "button",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "address",
    "paragraph",
    "list",
    "unorderedList",
    "orderedList",
    "defList",
    "listItem",
    "defListItem",
    "dt",
    "dd",
    "dir",
    "menu",
    "preformatted",
    "div",
    "center",
    "blockquote",
    "q",
    "form",
    "input",
    "table",
    "colgroup",
    "col",
    "tbody",
    "thead",
    "tfoot",
    "caption",
    "tr",
    "th",
    "td",
    "teletype",
    "italic",
    "bold",
    "underline",
    "strike",
    "s",
    "del",
    "ins",
    "big",
    "small",
    "subscript",
    "superscript",
    "emphasize",
    "strong",
    "definition",
    "span",
    "code",
    "sampleOutput",
    "abbr",
    "acronym",
    "bdo",
    "keyboardText",
    "variable",
    "citation",
    "select",
    "selectOption",
    "optgroup",
    "option",
    "textarea",
    "fieldset",
    "legend",
    "frameset",
    "frame",
    "noframes",
    "iframe",
    "object",
    "label",
    "anchor",
    "map",
    "area",
  };
}
/* JavaCC - OriginalChecksum=cde22287f95bfa4f787fbd91beb3027b (do not edit this line) */
